name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install pylint
          pip install -r requirements.txt
        
      - name: Lint with pylint
        run: |
          find . -name "*.py" | xargs pylint --rcfile=.pylintrc

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: log430_lab
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest
    - name: Debug import
      run: |
        python -c "import tests.conftest"
    - name: Test with pytest
      run: |
        pytest

  build-and-push:
    runs-on:  ubuntu-latest
    needs: test
    steps: 
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/pytest_app:latest .
    
    - name: Push Docker image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/pytest_app:latest
